# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:XcTugDzWEZarfQo4UlfKg7vzwE2gWg==,iv:e6gW9NxntQz6QiDInddcGnagTzqBNW52Qob7B7VL+Ac=,tag:SsCgeoLkZVOJvVLc4n86bw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:opPe/XWpJ7VdE5xFQhdGMLLot2hWSLbjUpFrz8ItJPPDVjgRhg==,iv:exbo/nHnj+4Inirg0iYGt3MukWhPWMBnNW/W+roGsig=,tag:hfd/QEkYxy10vc5iW8bRMg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:Z2B8I+MawMw6m/0okJMwH2VO,iv:Orl6MouXaf/+lOBDLaQC6preMcT1Rr+MG7qH8bsK1IQ=,tag:H8Uz6gKJZ8Um2LKtwLwN4A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTVoxZFcxeFJ3RXE5SWJG
            R05pV1BUQmMvc3M2MXZFTStYY2hJQzVocFQ4CmtPUmFCcllBbVBMZlpOaGQ3bzJF
            QU4xaFZzYlVac1R0cWlsdzkwVGYwdDgKLS0tIENEUytKMTljdHB6UnhMRFhpbitn
            MkgzYjBGREtYTldxSjZQc2VGT0VuRG8K1sRlBhz3audg1gzKIXsZtEXqTAyBIf2P
            7XRZ5tQFeezlJHNhEj4WQDLhae2SuO//yoknwpoGg17BSQGQuteC+w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-12T11:48:16Z"
    mac: ENC[AES256_GCM,data:f2GWV1jcDyQJSmO7PCwcl9I/qHI1G9khiNIUPQFj4/TmM17C5vus0bWyPlhAnT5SEwmTIJeH76mopgcdhtLjJMU/c0DoCbmuRIPCm3btSLIPxwk+kgqd4MXaLg+NfuJmCdpStxuhXknQqsXWomUZzkRVJZQysGCjpkLc00CgDOM=,iv:vnmjo3/jVuW76d741OflI29NBkOddNUHbzlrtpKE0S4=,tag:rnxw9yPrhU0VwOKzqzvJGg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
