---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kured
  namespace: kube-system
spec:
  interval: 5m
  chart:
    spec:
      chart: kured
      version: 3.0.0
      sourceRef:
        kind: HelmRepository
        name: weaveworks-kured-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
  #   remediation:
  #     retries: 3
  # upgrade:
  #   remediation:
  #     retries: 3
  values:
    configuration:
      annotateNodes: true
      startTime: "10pm"
      endTime: "2am"
      logFormat: "json"
      rebootCommand: "/bin/systemctl reboot"
      timeZone: "${TIMEZONE}"
