# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: flux-discord
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:8J3zWW48e9iK1+Z1XCQ4ZX54wQJ7ZssGE2k43psN8xxtCGYmk9ymP8aQXawBp5+0gTeosGP9pGFY0NrxGWERzwIBb7dwRdfRh8spSb6uXjXw8EljQDExe7cHMShQUEhdxQ1X5tPQhlLjtFxRbZnXdpmp8W9ynzbL,iv:ZqyhlJCAYvI8nwZKoVNKABWBtuHZRhH6Q8yZiKKhP1U=,tag:YXwoM68ZmCuglbzDhsW37g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4SitjdGJsdVdadjhKcG9P
            eThTeDkwK2ZYQWdxajIrbFlJMmMvMzZnT0ZNCmMvYUtLT2NIV210WThSQmdFc05j
            WWRvQzlZUmgxdU9CZWc1bTlWa1kwYU0KLS0tIHNKWmlYOW9nZ2YvVzFoQTVYRkEx
            M2dRa3VJYUFpbVVvQTlwcUUvSnBaMWcKJfu6TdwnaFCvPlq7fY06Yztd2JwWpavL
            xHDIHHs6TIXIMGt4EmsNO86RYCz6IfYQrNAzXV/holg4MCxXggU0tQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-07T10:07:40Z"
    mac: ENC[AES256_GCM,data:2uYdQFZocxXOoS/lrT45aIplTknaT7BoMCmz1L994wexI8+7R3MhWwMpg/nUIr0HPB9q4g2ay3Or8dPgN1vzUp33CKR9VI4kaJWWiIqg46mNjImXoOM9B6kfgfUayTmxbmboplMzznlKkFr4e7W+bQ1Kx0WkbVGKgWUKGW3j8nc=,iv:NQNKSPWMqyMB2BIhE7uSM3UFtts2ugmR2+jlkTkGlyI=,tag:8PGEoNOWiljGPGmk9h9Wcg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
