# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: networking
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:PlJUYSp2hL4Chy1YqMevDZaZuDNnMA==,iv:yuSEDbgR+N/mQKgFNbmPpDF7MLxY7yKqnvbOsVhGVsk=,tag:dlcIgDuAWjBCs8WRb+5zRg==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:ahGcTGXlaW7Re6JRjo/kUWlCSUeFuy0fmuUDuv9BP4EDTes/bA==,iv:wEsWzBwbvY+ji8hnVVTCq6dJ6xg2RdSzizea2/QYG2k=,tag:qDHPa5uy+NMm5qDgPUZH9g==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:4YVvgVH0CgbsxFiWPeqmVJyr,iv:7AAxHmeAVm5kj5z6Wj51Buyzglrfzte88E12YWsP6qM=,tag:9A3aDPwQkJzRNn6+LPJ1jg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuWWFjVHEyYUJkbzFvZWxj
            VVVFMnd5NWJ5UEhvR1Q1ZUVHWUUvVnhiOXdBCkk4Nzd6QTRReFVHSkpyZVM0UVhu
            U2YwWWhaNXlYT1VvRE0xV2o1dW9YS0UKLS0tIFduUHIybTBXYm1MdVJUQVBGSnBw
            TmsxRUU5d0dOTXF0Sks0RW9SNWZWUGMKf59sB0sFs30MvD7CkxbEUULlbXIRapfs
            Lsoe/QxIy3NZ1yJiPuddREqqei3/bNt+Plfnzpri1gDLRI6T1tYPGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-08T12:38:15Z"
    mac: ENC[AES256_GCM,data:4WRgwoep9vz/smE26EKbniU97bBXw+NApePmCxy7hZlnpPWT1UAdVwFfilmN8re76JHI8QJnFUONUcM0dbIztZe4hxMT9wldPMHf4JfZPhLyAqIpfJPLpl812Q4ftodvV8u+BZ6sSMEIIhOfcr4mCqZHdxT4OrOFjPwNKPGvpVw=,iv:zbH4j1FASuIctyjtVgxPML7hPcNNlY9/pSgZkPf5akc=,tag:opYl7EI9XLMJacPZ0ToNMQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
