# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:IXWMPfrHLx5QzhT5VYSI+U4poQvy7Ogaptt7YWcvcbCc5Z/XFRZ2Vw==,iv:e6PqN26U63dq56zV6w51eRFFqsYqIVo4tY0SV01X6a8=,tag:HXUE1shP1AjBFeHF0DzQVg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWRnhZUzBFeFVSaGlESXZJ
            dmp2czJzd1REN2FyVCs5VE14anE4VEJkbHlNCjRqTTE2MHNieWFIZE9USzlZRTZL
            ZTU3ZDdGWGJsTlJOOXo0Y1l1U3lJbmMKLS0tIGlHejgrVzc0VmVlbXBjUUtKcGdk
            ZWp0Uy9TV2cxUjcwR3VMU2JnTEdMWDAKzJrwrbBPuwbvStM4NaWbv9FsrO5kSxq0
            aArkGbb/NeGzOT3UzGZh/zkAwXpdqO7JNqj3liI1COmHHx8Iiifb8A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-14T22:17:22Z"
    mac: ENC[AES256_GCM,data:80Ekw+62Cu2uRCznO4iMiuqXf9kvydKoL1gFGflDVbW04lyaZEjsM/rO7ret5NbNWmjJuvLypl5XZGcdK2kb8Ac4PimsZBAYt7jtKIHOnShjhfoXgSyJ4rDkbneQ7hdQw3Mzy76O1AXgrQ/9qNi5x3LbK130/qAvQ+xIQsyYeak=,iv:tz1B01iX12VVdx3+WJq0WFEI0D0BNJz04ob+L2og2cU=,tag:WkFeG2uNtq1Jbu5LRIereQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
