# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:d9IL5IsaEnwGMTT3B5VKMKrslqPPs+KRgsJ93/FN1eiNsF2pO13Dew==,iv:VkzW2GHadnNIFUqOag6Raam6HhxwHWqSYmmAwjIrgzo=,tag:SxL5jrh8441Wr1wTXMlPlg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYzR5eng0ZHNxQzd0SE9K
            a3UxTXkrMnJuenJKcmNkTTlnU2N4eHlLL1hFCldySU01eEhDZnIzVEFJQ3UzY3gv
            bmxiNnBIeE93QWU2WlFFZlpPUkNuekEKLS0tIE1CZzBybTJ6UjM1TFl5R0FucFNF
            a3J4dG5pRWdHQUVMbnJ0dUhQYTZ1aWMKFrF7ko8bh+HzybzGAsw72KXgt3Fz4Roj
            Lw4+vq1Z/nxofEQ4xlnm8UPyyA37Vun6VXlFP1+I1d2AFUyoUXP0Fw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-12T11:48:17Z"
    mac: ENC[AES256_GCM,data:7OlPgblNAZcFR+dHIVXAklcHCQd3Q7NvDSHTwsEzWQKZjas98rH1Tr8hhXIBJYgstbtEgAypB3EGAYw94/eZM+KNkmZBOKIFb5jd86XXufYiBVFuTj83U1ejJBms3WznVHvwFGgf1xZBER+Z4DTwzPV16+9mHWGBn7amUtqLjfQ=,iv:FlAqNgi1opoFFm9kBYNuEaipQHdIOUDDurObrIQ25WI=,tag:tkuBFVXDIgQ6a1geqGX0ew==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
