# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:u1W8BEromD1Zkr/JqgYiiB7FTGj8jzmTVpqjYFyw+GqTGhbRdgxkeQ==,iv:dutJwTkpAd7AMqjKeA3dbK4/b3cfK7jT8bTQbwDf2Co=,tag:BtdMTPO7jjPb8Vs68k8WnA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLMExKV2RwRThVb0FvTFV0
            SldBYlFxa1p5Nk5nbGN4NENueEsvelhvYVJrCnhLSVJ5WWhza3dJb08wYjBqT3ls
            c2VPeGs4ZWVuVkV4U2xjQUFQRnI0TEUKLS0tIE53ZTQ0ZGxxUU5mQXlETm5BeERq
            NG5sbmo5TlVQUExtckQ2bU5BY1FPUWMKNBkk0zJOoXsUoOzZW9vO+OdxOfL9npDy
            UgCOIqTt1bcRKWw7sQ1jPIdIc+9wu3ylG+h3/nUOwADNTB9EQZOUHQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-12T18:47:54Z"
    mac: ENC[AES256_GCM,data:Rq20SmmBLfV0u3OnQLl1JOhQaMlJmbAW15/Dk6rdu/OsBpPWpstcEWcPafy2DCi57eQZKPHHsDp3L1Jv4O+yv9TPkua+Ahi0G4ByObXktGLnXTgPvbsMId04T4qU6/eRfTWLZdm1oJ2kxiApCX+gllAm38a6qAhOukGbHVZRavM=,iv:rPMriZyGqp+OMhBXB/YuWbu5eZ0ts+Cn04fDAItkpVQ=,tag:gkgK8if5O2LreFwQiu2zPw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
