---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home
resources:
  - namespace.yaml
  - emqx
  # - frigate
  # - home-assistant
  # - node-red
  # - zigbee2mqtt
  # - zwavejs2mqtt