# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:6R/AXHNYHsumUm7K+1nJE7CmHQhwwQ==,iv:8e2BkvN7c/D0cq6oGUSHt0DATkvoVCm69BLRVMPhdGU=,tag:g4+jriyPnwQVkZ615X1uKA==,type:str]
    api-key: ENC[AES256_GCM,data:U7VNWa9C2mBb8OnuugnBIt3YI9FmU47V9fKP3FWfx39RIul3QA==,iv:Htn+mPOF6OQ5HJGt9GKnm02UR9fipYM58gSq8x9ELYc=,tag:XmoKBxe3VXJYrfx2e+7DFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBSWN3c0NhM0ROTzZnTWRC
            Nll5Z0VvcGlUa0xnek12TTNCcDFCU0ltYldVCmwxRzdqMUpMa1dyYnljcWRWVFM2
            NzNENXBvTktMdVhWNUd0a3ZHaGQ0NGMKLS0tIGJLdWZReHNZYm5TUzFIdWgzMEs1
            eDRuZDcrZVBiSEVHSEE1NUphc3BLZTgKJX90Z1jWxV2RJVwahlRPP2ZRv6VGCC6t
            7DqwyLEf5K42tYrvIrWkPjtPio7P0FXmakDaeY6frLC4BKD2Wyh0bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-08T14:36:05Z"
    mac: ENC[AES256_GCM,data:D23QdVFjohWgD7CHdZfIxdnVU3tmXXOzoIrXZqn0Z1gNf+P9FcQCkC6UhtXFWrZZFTGOLHthBSJqv1xqefX3aFfjx+loREHu16fEk0WJp6GZs/sdqKBinpceqcziqkUTMEvBw8wXfQThZNxCUezes6mI8MyhdiuPrdo/CDxv++w=,iv:TSIP5Vm9kmxI6s2DFMBEVZnmp28wHZOAa5Qw2zr4RPA=,tag:b03j157xeKA9kKHn40KuKw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
