# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:fJ4rrz5YbYhruiXh7g==,iv:8c1zC+vPR5gwdsIXlbMeHBx50BsuN/X6Vb5xxlCorsg=,tag:plDi8lwKCjpBkMX2zaKktQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:Phyhrwqvx9TTf5u+MKAPPbUws1yKTA==,iv:Xzav1SCwOSCGmxihCq0x4xOJsVh2IV6XEQaToYkWKXs=,tag:XGzGZpthiuu7hR9hBgcsdQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIT1I4YW1sUkJKNi9QU0pT
            SWU1cktFTlVyT0kxZlU4RnlRYlZZOHUxVldrCldCaTBmanpOb1hCbHlNWWxRNlhW
            VWdXTHd1M3VTSDJUamVqdmRZTE8zVzQKLS0tIEZnSWY2Q2Q4L0VhVTUvc2VjaThj
            dU5DbUZVclBlVEs2Uk1YbzJMby9ld28Ky0P3GKRgnw4HgFIyvgHv9wgSuqOhCm5B
            Zr8ab1bCZ9OTjg8jWfWkJUclbKEHVGyPOqQcISKTFDE3ljw37Kj1ng==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-13T22:28:29Z"
    mac: ENC[AES256_GCM,data:YMmWt2/+yAAuutyfhiNp2Kjqj3hsJc8pfZNIPFxkLFahlPc8IJRshbStti6/xdAQ11EEfWlh2MPkkw3kULFnjztmyeUl5Tc0JTQDXlQtyizqP4mf0QYv7Dw60YaCvPGL4llyDQkovjJrT7RU9f1EXkGEcx7fqutAmIq4hp+Uk3o=,iv:o0W88EKnOO1bMhYKXUrF8A9LAF4xui60YHGdKKTm56M=,tag:KMh8xRszbRcmYjr0jhCsqQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
