# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:DxbOkZANBQYL/RoRSg==,iv:WU0nEU1+h5TV+UUbE5+Zfc1zx/8zwzBWR456+rRev7o=,tag:KfVC+KcUdeHHwuR1oXUC9Q==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:md4YzkFGDqjAEZF+8KuFY+OqsszCTg==,iv:ptskWAWRIj3itWL48R1UIauTdCS6A5GTKIFNcODavyU=,tag:HCRGA8thN5xhkflR2FQwhQ==,type:str]
    SECRET_CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:YZscyyLSalmehaZcFOHy9NdhErUaxz/8iDQdzwkUmNOzusaPcw==,iv:MPCvEcc4AOMN5yFcQcN16JC+J3/UEgOBEdM1uLf2x/0=,tag:BHd4RHYmsxAjhdbYLCYTXw==,type:str]
    SECRET_CLOUDFLARE_DNS_API_TOKEN: ""
    SECRET_CLOUDFLARE_ZONE_API_TOKEN: ""
    SECRET_BOTKUBE_DISCORD_TOKEN: ENC[AES256_GCM,data:CgNv4C4Rs5IgqiZtMufZGM7Bmy9bMwgmmYNC2uzDq9LBaHQ0dJ2o8w5QAJapvCK6//ehXH8k1FnIluM8Knf0FjqYXN2p1w==,iv:4wc5XXhqk86Hn/G9PFR0SwHrmysibrz/P7JjQiQAPoc=,tag:HdmMZkD7mteAwZ/rTtJ4IA==,type:str]
    SECRET_BOTKUBE_DISCORD_BOT_ID: ENC[AES256_GCM,data:jZUaUAfGc5YWkX60O8iCh1lV,iv:UWSTaFgj57iRDsJuiF9Fz7B0WidL/5OpswPIdWzhxnU=,tag:rKMWKQPngjJsRYZEduDicw==,type:str]
    SECRET_BOTKUBE_DISCORD_CHANNEL_ID: ENC[AES256_GCM,data:c8kgKD4mcoTuZQo38x4FycUn,iv:9jl8L4mc8CKduQaL1KVPQpOcHPGjL20NW+HvsiImk4w=,tag:DhM1qIhW7nu2ESkxXttP1g==,type:str]
    SECRET_TRAEFIK_AUTH_GOOGLE_CLIENT_ID: ""
    SECRET_TRAEFIK_AUTH_GOOGLE_CLIENT_SECRET: ""
    SECRET_TRAEFIK_AUTH_WHITELIST: ""
    SECRET_TRAEFIK_BAUTH_MIDDLEWARE: ""
    SECRET_TRAEFIK_PILOT_TOKEN: ""
    SECRET_GITHUB_PAT: ENC[AES256_GCM,data:GeL0TqUoWCsOMKKz8+Obqi87lfFOd9QAEdhwOjzI/zqASrJprRCmHQ==,iv:M1IPM2twp8cw3abkq9m4y+KSavVnO3LD0QgSDWmCRG4=,tag:38aceW73kKrE3jpEW1uDpQ==,type:str]
    SECRET_GRAFANA_PASSWORD: ""
    SECRET_GRAFANA_AUTH_GOOGLE_CLIENT_ID: ""
    SECRET_GRAFANA_AUTH_GOOGLE_CLIENT_SECRET: ""
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ""
    SECRET_MINIO_ACCESS_KEY: ""
    SECRET_MINIO_SECRET_KEY: ""
    SECRET_1PASSWORD_CONNECT_CREDENTIALS_B64: ""
    SECRET_1PASSWORD_OPERATOR_TOKEN: ""
    SECRET_OPSGENIE_API_KEY: ""
    SECRET_SVC_TRAEFIK_ADDRESS: ""
    SECRET_SVC_SYSLOG_ADDRESS: ""
    SECRET_K3S_CONTROL_PLANE_ADDRESS_1: ""
    SECRET_K3S_CONTROL_PLANE_ADDRESS_2: ""
    SECRET_K3S_CONTROL_PLANE_ADDRESS_3: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4UXZTNjRUREZxeTVwY0pz
            V1hUR0Y2NWJvYklKYnhzSGNtbGFpNEpFb3dRCkRSQ3F5VHhBdkxTekQ3VnJQZDNG
            cUF0K0svT0h4WmYwZHJqZ1RtRm44ZVUKLS0tIENsazQ3UmlxaWg0WFYyWXJvSkVn
            UWwvM1pDTGVCUGJFZjQ1UjJkb1QzSUUKkR3I7CqoxYhcfqz5z8ODaFso204jtYwo
            vO9IF7u8HK7PNyg4DbLeL3iREu/+jvmW50ilgfhVrkid9RmOjYNXCA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-12T15:55:40Z"
    mac: ENC[AES256_GCM,data:LMG0FaigBbqvaHhO82rBhMg+873zdQMapsMHhDvKmnIOCpYC3q6ah8n5FThOsc591zlaa+GdWolOblbVS4AIOSDWYJIHBpl7FAinsPotClBn4uDR0HtwKWNfuN2GMvLFCA7Np6EFdTfe2rcYjDoXEW2QE56dw23MB9m0Fa6pD+k=,iv:0uGr+XPITZREOAtCmxm1npI3AZQ69GgsLv569pFWNwo=,tag:uuKodN0TSJwjgKgjWm84jg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
