# yamllint disable
apiVersion: v1
kind: Secret
metadata:
  name: discord-webhook-url
  namespace: flux-system
stringData:
    address: https://discord.com/api/webhooks/983478725708480522/N4T52SB5PhixQtPF8y5dw0ptv2mXv8dpyTyLC3zBHXDsmGIBgZmB92Dq5Z6kknedZ0Tg
