# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:RQN9e87VSMTgJHa65Ov2a2CpjVeq71ReJlp0XVi9Waf+tL0nkq3/XDa8Pt0Qe6ApxnXftbfIQWGA9XoDiLCuy+cZ0SoS5PlE4oglJ4O+xRarAC2FjU6exIT7uv8wfCqct9pQ3+HImiDnGA6dFyuQUafLbeOiaajX,iv:pbGEl2pJkErmg5Koq2LS38P+P0FMbXqu2VpIUBZa73U=,tag:mLpDlNlbCRbL9rSStDkFuQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzbW5ibU5tMmtxaksvT1Ja
            OFRZa1RyMlJXdmRPZm9qVjlsbjNEZ250eVRBClhhV2NaQnFJT21oZHhkVStyT2ow
            aHZUbVpUTitud0lCQnhheWgvNGFSZlkKLS0tIHpIekZUaVlWRUVjYTh6OTFGNEJJ
            cDhJZ2syQVdUWFEwdm45eUx0UzM2K3MKR1veJG6oG/FBjxi43sUn+saPKkkRRQsY
            om5NRTbEzmjpN+KFSqbvkF7flo1wsbfnpg6VfDV7E223pP/FvnuQow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-08T16:11:19Z"
    mac: ENC[AES256_GCM,data:wMeg1oB69GbxpClFuE6X4m0Luo+7IVVTxkDclZ66JuSWNdG73LbXCLV9SKPuM2oSyyWkxBCvkMNuUnAwuTBLV6UiYJyOXiqRV+GNXM4oyirtE6Ad7nDSRiFkuZvs3y1xOCh5O1btxmmg0QWS2tckIl7mY5uDOcEPk0NMvryAWwg=,iv:U2NZlwcyeU6J2DxzpUPMTuzIrHd4bBK862rksP8XiTI=,tag:igE9doA1jBQcyp/Mc0rO7A==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
