# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:DBxS374WqLVPRE2lGSKMDXRJK0IdNz8zJ0ugLLZvsAcqjR1LHWDxG28f2i1nyPSWgj4Ez+rI8oLyN8O8ge2BkVDFLhvX9UFFj5+XWqhoLwQ3pQWtxURnMKXiRV06elAY/NRRInLtIXm08Sf0WjpX7ERwKewSOHT9,iv:PfWdk7reRPpu/11kOPp8UvNPKsRypVbyRKnL7EJcfr0=,tag:zXtmnQLlQ/9jxh4VzIc2nQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2bEFycHlnYzh5ZHNaWlRi
            eXN1UXFPRHd5RHRFMCsxd3lHRllyZ1l3c1dRCkJLbXI5UTU2Q2orbmdHb2VEZUE2
            NnJjS1Q2VVZ4VWVaLytKQ0pmbC9jYU0KLS0tIHR5VHp4dEo4RzJybU1EY21mWmFM
            ZUlyNnRWVUYrTE5TQ2JjenZSUUQwaXMK2XedBzwYy5EawjMVPcSnKqQ3VW4MG9fF
            Bkpb9JeograHjeJBtUEZPSK/7+5R2i4MRXa4mKEFIuJG/81cLMJDsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-12T18:47:54Z"
    mac: ENC[AES256_GCM,data:k2EXHNTn+n7DSV5sInSImosUiJzjH0jhj5vaJ+DVboH+YzP48Gh2G/INZ6Dnl/1iaGm2VUNHSFddfAG2AHS6K+p4fOWp5WtP1dIQ4aCuegNYQfkgI6ja9n4MvU7L3WQoy5PdvmpuXHTKTUfcVxPqMjW2Je7652erNE98IDimvOs=,iv:BZeWmwWaYrBcCPMbZZBMml2AyhSddOiZ8h7PtvCE/7c=,tag:r33Q3WW4Om9qMbIwSdNKEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
