# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: discord-webhook-url
    namespace: flux-system
stringData:
    address: ENC[AES256_GCM,data:F10olvaPD29KmINkaNOezoyGfHR3M2KDwujDkJ5dJYXXLuz5/s/+7rWWbaQBNh8QIx9Z7TZvzH+wJAAlw1iMHNJyA8d3+5Z8IuiAC2coNdIE79CO1zXJzNV+LF3h2VgvF5/SlWoX8J8SHKTU5TZJGZzIKNgTPjnZ,iv:SEF+ozJFEi4WDiD8Wl/3xECaOuLar/6Z5h+qAwyyj7U=,tag:URM93BbD5g8fg2zEycKOEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzWUphMDYyNDJuR3dXYkMv
            ZTRwR3dkZWg1V0luWXBhbTgyVHpnQVlqT2xjCmRWN0srR05ZQ0VocjdZRDJqK3N6
            SDhNY1JWWDI4TlJuek9WdEJHM1A3ZWsKLS0tIExqQkFnYWV4MjJ2dEE3cVdJcjRX
            Vnd5RjFKMzRxT2hYZGhRUG9tL0wvQ3MKu4q9VOFhqzxx6a2/z6gXBxLoGhMLPqEo
            3T7DdDA1HrRTAqUciWPrer+8tqsdA+adO2LSFJV8MncxJydXlFjfeg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-20T13:22:25Z"
    mac: ENC[AES256_GCM,data:lxjEdju+Nf84mzq3vFkgnAnj+GWqwU7VPxoTH6ZeDAxwO//CeSmyHBp0iZYTCxnto6Azwv8ECgTvVCNtm5wzjYzYHiu1Nn1qn7rykuwf1Ikp4hE1CNJeveXKfKkSLKQKtWwA2VVqA/bc1/FxYlPJfFPrcJBieF1wHB+A8BSllYw=,iv:Cx9OtVqPFF6ez1hFfV6IfOXlEnlQrhjtUwouOczxCbY=,tag:7Xsr8lPgYSPWeKWLEur2/Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
