kind: Secret
ansible_user: ENC[AES256_GCM,data:rLA=,iv:pnbbsPzcr0wJrQ+wz7Ynen7/DZfxoz10e3Uid/85iQQ=,tag:uuXADp+qLAGCofRYlmoRhg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:vgRM2sUBl5k=,iv:pOPqIsIORJqXJ5Mur1pljNVXcfVeNhYEawyOrGwAKms=,tag:DMn00LM45rkK0KG/CGWsMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0anNJUnpEWjZrVXczTHVZ
            bUxCSElyOFNadnJiVENVQTI2U1BscTk5cHljCnN5Y2pTRHhvWXNqV0hJM3N0T2pC
            ckxMYXBNVm9OVU9iKzA4bk5hRjA0K1kKLS0tIDNqMSt0TVgzMGN6YzIzRWZ0N043
            TE82dW5tMFBET0Y4a2JtZEl1Uzh4Q2sK/KYQK6/mT+0pyNA0XZ8DMFp4RJ4MLOwg
            8D7lD6GVPlzGRqinRiVoaDR+Jib1AxpULb7hKdNsFQOR0NTwSQ8mvg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-15T06:59:49Z"
    mac: ENC[AES256_GCM,data:Nw68wZ/ZyHobFhUDOPbeSB0TMQTM1W//Vb2hZHavH9E3AhclG61r34Qr0lXwk9hZLx6d+DiRItzsQ80Ir4uHqecpxGyXRAWVXM32rBevHEKY/gWiVLrMdETRC/zcx72WVSLt/33dWWPLQbmUqWCkCNgqYGNpAmpk+kZ1A/wlqFE=,iv:woG5ANhC+azQXUOrfA8tD3UzRRKDapj7s2H/tneI58k=,tag:zQDJ2l0Xf+F/5VQNYQka5A==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
