kind: Secret
ansible_user: ENC[AES256_GCM,data:Mbw=,iv:qe4ZLXAGNYdbMNEYeQCY6821QL38LYooM+Tnt3uzUfI=,tag:WiBC4tBq7zvexjESqZHzaw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:HXjTLTD688k=,iv:QMkAZ+APR7zKJSyzIY8fZupBxjAmRadKgkH65rJyKIE=,tag:YpGY8G3bTkQ//Y6U35mdMA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMWVVub3NMUHRxWkFCcWtL
            cE1Ka0I3cVZGajdweEVSeFZydml5TGxEalNVCnI1NzI1RmR5LzZWcHp2NGNRdTJS
            Wi9XL3NWdFc2S2RPNnp1Q2lJckVJL2MKLS0tIHppRWhwazBVUERkaW4zenlOK25x
            VHAxU0ZLSzhpZE5PNGUxbFRBSmI1S2sKY8WyaiqOZ9aa0QdIHYRPDNqgrAJfw0Z2
            tyyDFvQY915l5DN39yYqhG4+5TqK0SJJSUpMhDyb/sTAvD4L8iAOBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-12T18:47:54Z"
    mac: ENC[AES256_GCM,data:hdsvWLo2TuWikfjlbP+lWlENoAY52a/e33jcF2trEjQnLHgOIOMd8MqvptLscToEe7VA0YPkkI11sqX93tR/PrmjSfKF843yc1jZIfYjOHzllAKV4vXHzKNdSER+47NqimKvJLgJQ8gXkaq+luZQQ1NAvgFmbG4OqoN4z5eCxdk=,iv:yWagL5c6jxiztDgHzlhF8VUCky1t0RGm5FmucDOLXLE=,tag:tcp8pnq3GodkvfhKRmoCvw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
