kind: Secret
ansible_user: ENC[AES256_GCM,data:svE=,iv:D0ZFW4XgLRclolRfnjqkmpAnIGYVPs819VqfTPGSVbs=,tag:t4PpRW7D7TGQNyyM/Lv+7A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:BY56o2odgk4=,iv:cYQX0ggZVbz6nrCxZL3GTcFy47+7O3gshZm7Ow/7GA0=,tag:+RbqSPW3UkF7j9pPOKlccA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqcXdOWW5IN2JKTTF6VjQv
            MDExMlh6MTgxNmJlT1g1VkxCeVBCSkl6ZjJFCnVkVWFTMnd1WnRiaVNVZ1RqRlQ2
            TUJuRVQ2amRhdkZ5Mllxdmw3Qy9Kb1kKLS0tIGtlc3E4bUhZdnlOd0ZLY0gvWThR
            aDEwZTdjUUxNeUI4bXpSeUxobEozZ3cK6BvpBwxD+qT41MMv10KBBE+0bhul4Y9a
            VgO9jx0niOtKO3mgU8AZDYBSS8SpMf8lyGgPtlrgqOPlOen/j92Z3g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-12T16:02:19Z"
    mac: ENC[AES256_GCM,data:YwCdW+BgHqS+Zp+4hwMUZRHJrXgHqEAcn7Zjixapqo9PpWmlS/Cy8FF3xMRONAb6uJ5ZFrNhSGxUaCxulj9Kk5IltonzgaKuxbJJ1zfKnQQqaRSOTfZkLpsy0GE8uN1IvrmHh2KKep673aHIC8Y9zLyFyFP3buKGbw6wte2XQWk=,iv:9bNaIVPv3fsdQ/g4L7LrrGCR3HpHS+2SEkqvgTRq9ZA=,tag:Zm50dCnx2i/neEBcNk2+Qg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
