kind: Secret
ansible_user: ENC[AES256_GCM,data:8DQ=,iv:S53zJ7ydSZWnB2Rd0D7xLfMVj5QFTRlRitQ6xyDiyYs=,tag:DfcwEKeqTbr189/mcKrZ+g==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:FhA91t845IE=,iv:uQNw495BAAbJP7aGzXGQHLlGRd2FOmlUPeZEihBc9Qo=,tag:enWmUAbGvPwIkqYQoeDCEg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBeHI5WEMvOHI1UW41bU8y
            a1h1K0JhZ05xUk1zMVRHTi8zSkJwMEFMdFJZCjVrNHF1Q1hlMGNGUVBOT2JGZXZ5
            TU8wUU1RMitIYlZFdTVMRVl3c2NlQm8KLS0tIHAyZTQrVDdHV2Z5b0JLZmYwM2VJ
            RE5wekxMTkxPbFZ4OG45NzJOYWdYTzgKOhn9jl+HyADy9VpZwtrXCFNxf5SbSzP0
            nzBXbhamOEtBss1HCl/3Ag8+viYoRRqxQa2kWKfiSFbS2mtEQQvgDg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-12T18:47:54Z"
    mac: ENC[AES256_GCM,data:ANtOXMMBuMvJzppFEzDMRxvHcitVPr5xmh+XGmDzdah/zH1i/02c/BfRixV9KZ/TXPoELXzoRmCA3Q9GIIgqwDZGKu16sxe+QZQq9UCrAclxBwW+UCA/yVIHyuVcDcRCgXk2o8FifB58An51Rv7Ln4YfY7YllvEpMgltSgmK1PI=,iv:8uMVuCr3n8qWywjmQxyjqvsHxFVZryfYFLJxjNw2umw=,tag:nmlE3idOF/6Sav1SHxkLwQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
