kind: Secret
ansible_user: ENC[AES256_GCM,data:ytU=,iv:QXokxVNEgjXMDLeFiZm3+ZZRaCdDmzmHqENdCrws6K0=,tag:HHsuxVbWFFwduxBqxsPcrA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:eA1hdQD0g9I=,iv:s7MFv4P45JaP9y6Z855j2Gr/lj5GmUVAM+ZkxQJwnvA=,tag:HbFZIvYiwFDM9NQZBIk0Nw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLT0crd29YYkVndW1ydzJq
            TEF6N2VtbHlCdWpWY3RnVk1RcXhiRlNuejNBCktVTktiYXR4NDBTRnJMbFJhNm0x
            TzZVWUVWcDNuOGY0MDhqUmk5SzBzNU0KLS0tIDJNTU1aamxwT0pCKzNUZExYdGRH
            RjJRcnVKa2xoSjlBSjFFSzJsZ3ptNmsK6ADLyKVDHmQKm8+ZMNz0M3EAdLoqrKPv
            +eDG5NbLc/00JYWcnmk4CBgYH9tCkbnZ6lzgDSa0SOSpva7u1wZBRg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-08T16:11:19Z"
    mac: ENC[AES256_GCM,data:P6pXjgizyOUTd87z7sWEBpdzOwM7UnymbI44Rj35J8IxbfjuGXKhw/BPubNHOpm08jQZoXU7EX7MAC5i1K0tk+dqTs389K/vshQcy/fTtFhDQnFbpVE+ciQOE+QRCgoyavbQtYQDVTECdb0JYjGRlgHGETm7fhSpHShwtpmMMuc=,iv:S9/yQmP7PSIa3FVN5a7XkYFzaKWGKWhvgDie9CcuwBg=,tag:acW0OPTv1ARsn+3caIp4bQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
