kind: Secret
ansible_user: ENC[AES256_GCM,data:ZiU=,iv:QT1FBVFa3CvQUPWSCNaTVxKfmPnP+dr+HseNJp+tCIY=,tag:7sxc8c8bpLHYtM4KZMHE+A==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:sAPUg73Kkng=,iv:wRIEJ4Km/dRROH+vc5visbY55VXQbW47hBvjSX5tK2Y=,tag:oJix0HePg94+b68zqRy+LA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqU0hRN3BIU0t1SlFqSVAy
            cnByYUdKTmphUXpuTnNMV3JmZXRQS084MHpnClRyU2hySE04djFKNUI4dFQxRmVY
            TlMxS1ZxWkpETGQ5RnBtNVlzNmN6UUEKLS0tIGt2RjdFTXVZZ0w3cm9oWS96RjJD
            S1FrcU9JakhpSEpQYm00eEh2ZEIyaGMKCQm0bGoTlbHNN//uOe42bci7D+4UjbZ7
            UuAQHXTPKppH78xnGNrW3KAZe9wrbSPynf2crjDDDOcvw4pMshYmdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-08T13:54:58Z"
    mac: ENC[AES256_GCM,data:Bk9N1vG+rtxaEwLZZRvu/huNVmDfr69hnx/z9Y0uU+AwaFNsY3KWn22z8tHhtFwQjcchts1z11Hzt/kGkGJ9BeuTh3kdgq8NQivos8Nndn3LadREeCJAPQ9aKWgOEvFLyK9WNu09mgDRDpKuaD8a/ZMPxp7aKgFdWzA+a5suYQE=,iv:zza3GwfA7hVBYUdsxqdEd5+y1DWulixtiRUMNSuqoTQ=,tag:Xddb6bXZotQRdJmn7YE4SQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
