kind: Secret
ansible_user: ENC[AES256_GCM,data:LHc=,iv:uF81Z/m47+RCAwyjQFOBlIsnALOUiZn8J4GkySyBWts=,tag:+eINrzcANMbTdDlzkhldMw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:U353JXCHYBs=,iv:KzAXydsRhWEaAbD90v9wrQiLDrrxNoe/fBgUft98meE=,tag:oGUSoybsv0WtCjJR71mgqA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNaU1HbDJEZFJNYllqNmFv
            MWQwWXU4aEU0dGZoaVE1Umd3L2tPTFo2bUgwCjVoclJ1Q3d6UUFqUWE2TWZLUXZG
            TXRsMGRDL0tNSURtZmQvbXgxRGhZaVEKLS0tIExBNjJ1QU43c1F3RXlXazJqTFdQ
            SkNpdDlIVytueVV3L3ZXZlBibmdUTkEKDwp9azvgSHdT6Gb1ztpN94RVNjh2iyLC
            ZhYOyNrDPrxlAsdWKRpPCsJnoWIaIqqd53faAYvDRC7TL3aVagkbuw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-08T14:36:06Z"
    mac: ENC[AES256_GCM,data:2Mt0E3y5DNfHKVm9acjpL5H2T1eSyA3nVKiaP92NlBHqqQEboJR/llMDDMft++/bsxS11hqHNCyykcr3mxSUXs+aIpDKZvPgDJxbCx8yJX3z1lbL4/ZU2kp6muBfpmoyNcyU8p9Jd6ykF240PJnGkESihyxns0LwzotQa/hxnHA=,iv:nzn9PqbhMUgm6l7fBFTwOGtWCydN0J/ssp1uzsjHIj8=,tag:bm7YiF+eDqhTwDmjLdR7pA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
