kind: Secret
ansible_user: ENC[AES256_GCM,data:82g=,iv:1JhksiPe8HcaMFY3nduvezQ0V1N6JpkzR3lCKvvov/c=,tag:Fmw8yWWJSTUVx8ptAHqoRg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:htiAt+Iveo8=,iv:KcLr6nyzYa4erPFH/AFmWl12GIoSf98Y8ctOV/GZ+WE=,tag:sx47ZQG5AGd38i52nIGKrw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGb1l4d0N1SWVsQlBnNGlB
            bDJkZUVGcUZLQjExMUU2d2ZMaXNLcnRiNlF3CmIyZk40VnNKK0VvZVl6ZXRBQ1c5
            UkZZbW9kb1NUMTVqZDRxWnhBc2s4MzgKLS0tIE9HT1pFREx2eWZGQ2JZY2RJaCtF
            MGk2RVVYTlM3YXRjVE95OUdJQjRhdkkKKKt6gQM0vm9IOyZv3WlOHZoCJOwAwW1A
            IDb2z/CmebC4C1LhiYWde/DzrI1pwIuUlvazxjWXduFViB/h2JRjxg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-12T16:02:19Z"
    mac: ENC[AES256_GCM,data:VSBfOh5pxm4JOTkqjIeC4Nqut4QIMiTaoEpn4x/ZkN+307dH5bpPaWPFC/2IHxWu4Ly5RsfJpXoREW5+j7dkA9KwNBY+pyrGRaoS8AKM6uN4BC6osuJPJIuNkHQRnsCYeRpa7xopBRVIwV3RUgWc7qcDOEQmrKMLuYbAsGqhTGU=,iv:hbg6ZsjOt5Wgh2ivUt11jb2QaqXzX11eBqBd+4RRS68=,tag:V/Ke1a7Q9GsYEgzsdr8QDg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
