kind: Secret
ansible_user: ENC[AES256_GCM,data:Xau+MBdc,iv:7aguWkRZbXq3v8HRJmyb77PwiDpgFKe+T44d3yPaG2s=,tag:FQVlav49vgc7i+A353eGWw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:dV1W4sCKLP0=,iv:UiCOdxn3sTNL7mNPa7Am099UhYlLQxihthwEWn0Rsxw=,tag:pK7wD+UfEYbiAIRcn0Mr8Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiUTAxZDhwbVFTTjhtNWZH
            TWdEaHBBNm80OThCUzhkQ1J2Q1FMVmhTU0FjCnFtNHZRczJmM0ZIZ0JqaDIvam5k
            NDJoN1dlL2JsTnR5RjFtcHp1VUkxajQKLS0tIElOS09xaVpCWDd6UnNDZlF5S3Yv
            dDFLajZYamdnbGhaRHRVaTNzNlRIY0UKS0rDXNv91WaLkOSgjOQ+D8i6/tjAW1k8
            7RuVSydgmiIhA5p10vN3UPbyKlBSaGC8yotxMPbwrYhTs+OjHsALxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-10T21:46:54Z"
    mac: ENC[AES256_GCM,data:BAqSU+EfwYD7gYiy8UIVYog3zKjScPT/W6/kNDIAn2YmNGZOhYDx9QBkSMHk9Hooc3PR92WBOslRxWPAsI7qH4IehwjX3stYxF1C/tkSHYJD3GQsGXyePEPx9d3UUMx8SSApgPwR049LWx62oeTqInaa2Qcdrz/ZQ7knJGfzkMk=,iv:ULBz2va9djzLqOGhwUe9PdB3OjJX8Mg2wnswcEvJuQg=,tag:u972jTMb2NRADdmPzdPs3A==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
