kind: Secret
ansible_user: ENC[AES256_GCM,data:BAg=,iv:GAUCyNXO94nrT+LyID8MOk/iY2/RBDiouRDXDHVnS5s=,tag:DCgJZrRH8dwFftL4YFUNHg==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:wWzWWLianU4=,iv:SHLAQmjbwvCsoV/AzQIURzYw8EEzZiWnklyMFbOm7f4=,tag:L7odfs2GXJridEMBimlqSg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBEKzdlWERTUzhHbnVmNUMz
            Mm4wL0d5SU5MV3VpOUJxM2dwZlB4ekRnT0VnCmZDbXJRd2czSWMxMEIzc2w5Q0xT
            dFAydzk4NEdtRGVxMG9PUThvM1ltS0kKLS0tIFloUmlDUzNxY2tnZmlSZ0VCRXph
            MkFRWFY1K21IMFFTb3VxdE1LTHRFck0KsIlcadjn3+GICLvfaRQP9YAx1BOzRHS/
            xWT+iJrE33m27enU3YlGC48sRXi9boyNEByUm/oHQI0YXcJZflgYJw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-08T13:27:56Z"
    mac: ENC[AES256_GCM,data:hIPongiSeTQNsvincwuZlcgQm8rn90RxiRo+iGloyTqMMtGGzRyuNNunl6edOSDc55ZkGXNw3gjV5tyNQ08+2+qGNcLJZnQfz8IGFtcg2i6lGIFSmaBW2LFnr5bGGGR+XaTopSGWuE0oGDCYqEuNcc8ixPXyTXc4fC4nTLis4Ls=,iv:S8kb5/92SCNCpAFGr5ir5sGzUfOhrQtidjHeJE21Yts=,tag:6l1Wbt1HVtURO6EkQMp0Ow==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
