kind: Secret
ansible_user: ENC[AES256_GCM,data:vZ8=,iv:98LEfi7n2OvJJ/zqBREaS20BeWG7HR+YxAgdq+t7CjA=,tag:ViPAJKXV3yW4GgkUGXdwow==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:OdFPsAAvC9Y=,iv:47omQrG2RXmb3tk8rr5E8wdE8Wmw6bkwJjFr5HSYiDg=,tag:qRVGM83Xkvuk03fCXyg32w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkNkhQenpQbU1yTzdRcW5X
            S045bys0dVRmUjBDNWNXVGp5SDYrZk0xclJ3CjN5b2F4L1NnNXNnVFlYa05heDZv
            YldXbXhuZFVSWE81SXB3eFVqQ0U4Q28KLS0tIHJRWU1tZ2xxcjV0UU5YTm03Nit2
            cDI1bEZteGR5bTJkZVlMWXJRYmg1N1EK9HigiXDfa9o3azi3cC+r9moK2+5ytnxT
            2kMpFtCnIVpmtFryD341s+96LXNPUOlZVlUkFqUkwRYrjcotAM9bnQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-14T22:17:22Z"
    mac: ENC[AES256_GCM,data:JSZX6h8bSMaoSKpfcGQHAQR/0O51z7gKzeM5MgbqIGtyBBJIfx3f1tlrd92khVTkKKKxbyxIgIYEbY7916Br0RCgKs+LysdFVQD4tEbnlIZ56Rv3Z6pppYE+rJorJsH322ZXuVV2F8Y7ZnPv8llBFZvCR1c/kSsmfm9gAoYpGbQ=,iv:aDuSFoOkwWdBdtWys9NgiGlzdmEuut9MiJMUhC+NIjk=,tag:zHOO1S22m9nv/wv1Ql/Drw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
