# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:wYUAShiv1/fHS55BKg==,iv:pmgnIEJzO4mkBC4RgUyfAvXbr3v3RhfttIvx4ZW0KQs=,tag:ghXsqybwK1GTjkgl4V3SGg==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:8BZbmILPPxxaaxZplcOES+RzdkX2LQ==,iv:EdYFnHengs6zITt0XGgXF7yRI4aot3jSZ6/9Q2KcSXU=,tag:4UYk0VLljdtCsTG7msWcnQ==,type:str]
    SECRET_CLOUDFLARE_API_KEY: ENC[AES256_GCM,data:m7MvRielDOrXQ0Wuyu3krBdwapEThstdWgJn6KOELG85D8CGtA==,iv:77b12gtQ2eIn2bIynXLEf9s6jTsN3WN59xW9Jn7A6k0=,tag:HorJ9dJXewws8/NTresMDA==,type:str]
    SECRET_CLOUDFLARE_DNS_API_TOKEN: ""
    SECRET_CLOUDFLARE_ZONE_API_TOKEN: ""
    SECRET_BOTKUBE_DISCORD_TOKEN: ENC[AES256_GCM,data:5GZ+b1uCHD8UA6yPJfY2thMpAaa0AKCdOpxR4FrpDx49Nuvmc2bwFB3iCr2Pj6UyIS8Y5zcV6AeIsNBSz+qXB3mNhcx93A==,iv:kqSTUFnHuSxJnzYxwWTl6hFBSB266ZE42Tz0QD7ZL38=,tag:0pyt5eqKVFRwZSi4hYYHgQ==,type:str]
    SECRET_BOTKUBE_DISCORD_BOT_ID: ENC[AES256_GCM,data:APldVEkchfjoPYYwwUlrnJQX,iv:Mb++nIyk+507e6PvLjTqDProebRIqNZB7mHOOAJ4Nlk=,tag:tx/OphYDQOuGbVTg8Yd3sQ==,type:str]
    SECRET_BOTKUBE_DISCORD_CHANNEL_ID: ENC[AES256_GCM,data:Y0pB9D7mwK2iJMBR6ZLzfG3H,iv:f9AkE5x2u8z7H7n1JJHvhsAQ1rbjdRbYyg8KLDM5cGY=,tag:+YSFS13+qdijMrFGxO5LCA==,type:str]
    SECRET_TRAEFIK_AUTH_GOOGLE_CLIENT_ID: ""
    SECRET_TRAEFIK_AUTH_GOOGLE_CLIENT_SECRET: ""
    SECRET_TRAEFIK_AUTH_WHITELIST: ""
    SECRET_TRAEFIK_BAUTH_MIDDLEWARE: ""
    SECRET_TRAEFIK_PILOT_TOKEN: ""
    SECRET_GITHUB_PAT: ENC[AES256_GCM,data:/qxIUCbiqIOubeGrnc5obnec4V2uyT6i9tbJLWAaxqQD0Yd5o45lvA==,iv:C7AF4x7UChccDWlj6UumxvdTOKgFNidSuujUpZA5vrQ=,tag:lmMX0TsCbr8Wza207nVG/A==,type:str]
    SECRET_GRAFANA_PASSWORD: ""
    SECRET_GRAFANA_AUTH_GOOGLE_CLIENT_ID: ""
    SECRET_GRAFANA_AUTH_GOOGLE_CLIENT_SECRET: ""
    SECRET_ALERT_MANAGER_DISCORD_WEBHOOK: ""
    SECRET_MINIO_ACCESS_KEY: ""
    SECRET_MINIO_SECRET_KEY: ""
    SECRET_1PASSWORD_CONNECT_CREDENTIALS_B64: ""
    SECRET_1PASSWORD_OPERATOR_TOKEN: ""
    SECRET_OPSGENIE_API_KEY: ""
    SECRET_SVC_TRAEFIK_ADDRESS: ""
    SECRET_SVC_SYSLOG_ADDRESS: ""
    SECRET_K3S_CONTROL_PLANE_ADDRESS_1: ""
    SECRET_K3S_CONTROL_PLANE_ADDRESS_2: ""
    SECRET_K3S_CONTROL_PLANE_ADDRESS_3: ""
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3alYyQytNN2IvbDlQSGZv
            UDlJTGlTOHBqUFdnZWxscmtmVXM2WU5ZaWpBCkVxYzFiK09DQjNvZFZKcFd3TzZ3
            K3JKU012REVoKzRZQ2liOFBiQzBvQ1UKLS0tIGhVNGh2bUE1bVY5bFJucUlrSjNB
            cytiZEcvODg1VUhwZVhyaDUxS0xRL3MKNy5dGaY7EwC4k9vkR/FcAVsGZi5PoBcM
            7kJJr98KSaO11ZUl+6k5+deddE8k0B5aPu/k0N2esahQfVW5K4mSUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-11T17:15:19Z"
    mac: ENC[AES256_GCM,data:GM3aQmGIoEESxeGRtv5c7q/8vv9dKB//tk9UTZHcoN7D5Rijr/tigVcsC9WAUr5DSif0PcCrl1HUhaPAV50K1qvX9GJZ+VIEkMteM3bDO4O7yRQ0mF3PALVn5DVr3zqtYkjyZnEJHey42USLP7jqwUDRPqSYseG57e6JmYbHMlc=,iv:pn9VIQx/eV6dtas9Ni8ouclBEcQAfVZ5EbmliR36cYA=,tag:+Wyq1S9+pI+6DNTW+qIRVw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
