# yamllint disable
apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-settings
    namespace: flux-system
data:
    SETTING_CERT_MANAGER_CLUSTER_ISSUER: letsencrypt-production
    SETTING_CERT_MANAGER_CLUSTER_ISSUER_TEST: letsencrypt-staging
    METALLB_LB_RANGE: 172.16.1.40-172.16.1.59
    METALLB_K8S_GATEWAY_ADDR: 172.16.1.40
    METALLB_TRAEFIK_ADDR: 172.16.1.41
