kind: Secret
apiVersion: v1
type: Opaque
metadata:
    name: emqx-config
    namespace: home
stringData:
    admin_password: ${EMQX_ADMIN_PASSWORD}
    user_1_username: ${EMQX_USER1_USERNAME}
    user_1_password: ${EMQX_USER1_PASSWORD}