apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-media-downloads-pv
  namespace: default
spec:
  storageClassName: media-downloads
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.16.1.21
    path: "/mnt/tank/media/Downloads"
  mountOptions:
  - nfsvers=3
  - tcp
  - intr
  - hard
  - noatime
  - nodiratime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-media-downloads-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: media-downloads
  resources:
    requests:
      storage: 1Mi
