---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: botkube
  namespace: monitoring
spec:
  interval: 5m
  chart:
    spec:
      chart: botkube
      version: v0.12.4
      sourceRef:
        kind: HelmRepository
        name: infracloudio-charts
        namespace: flux-system
      interval: 5m
  values:
    image:
      repository: infracloudio/botkube
      tag: v0.12.1
      pullPolicy: Always
    communications:
      discord:
        enabled: true
        token: "${SECRET_BOTKUBE_DISCORD_TOKEN}"
        botid: "${SECRET_BOTKUBE_DISCORD_BOT_ID}"
        channel: "${SECRET_BOTKUBE_DISCORD_CHANNEL_ID}"
    # serviceMonitor:
    #   enabled: true
    logLevel: debug
    config:
      recommendations: false
      settings:
        clustername: home-cluster
      resources:
        - name: v1/pods
          namespaces:
            include:
              - all
            ignore:
              - tigera-operator
          events:
            - create
            - delete
        - name: v1/services
          namespaces:
            include:
              - all
            ignore:
              - tigera-operator
          events:
            - create
            - delete
            - error
        - name: apps/v1/deployments
          namespaces:
            include:
              - all
            ignore:
              - tigera-operator
          events:
            - create
            - update
            - delete
            - error
          updateSetting:
            includeDiff: true
            fields:
              - spec.template.spec.containers[*].image
        - name: apps/v1/statefulsets
          namespaces:
            include:
              - all
            ignore:
              - tigera-operator
          events:
            - create
            - update
            - delete
            - error
          updateSetting:
            includeDiff: true
            fields:
              - spec.template.spec.containers[*].image
        - name: networking.k8s.io/v1beta1/ingresses
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: v1/nodes
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: v1/namespaces
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: v1/persistentvolumes
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: v1/persistentvolumeclaims
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: v1/secrets
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
            - update
        - name: v1/configmaps
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
            - update
        - name: apps/v1/daemonsets
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
            - update
          updateSetting:
            includeDiff: true
            fields:
              - spec.template.spec.containers[*].image
        - name: batch/v1/jobs
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - update
            - error
          updateSetting:
            includeDiff: true
            fields:
              - spec.template.spec.containers[*].image
              - status.conditions[*].type
        - name: rbac.authorization.k8s.io/v1/roles
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: rbac.authorization.k8s.io/v1/rolebindings
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: rbac.authorization.k8s.io/v1/clusterroles
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error
        - name: rbac.authorization.k8s.io/v1/clusterrolebindings
          namespaces:
            include:
              - all
          events:
            - create
            - delete
            - error

