# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:/sKFwPABGCr194LOxGGYDel2/JH2SJBVNEO28TDXG+ZwfU7lDM1Qpg==,iv:boQ9T69yaV+DivoKHkPMPCDwxJr+Zvme0T/kt8QuuWc=,tag:6zl1R6FljbT357BizkWRQw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYVnhPeWhRaGJjMGZPQ0Rk
            VHhSMWwrYWhZSE11c3haUFQ1QTlEc3pzNEIwCjlCSTRSakRZd1JCcWl5RXZqSno3
            RS9pVmlUbDliQW5MNWhjOFliWGRORXMKLS0tIGNnSDVyeStPczd4U1d2R2twb1Np
            Uk8rUzBVNnVWelFuNlU0SFE2cTBSZVkKmkeb+6ZRN0cxKWQzGYB1oJBBj5LqzlEb
            ebQUvFs28WSWdy9VGbRwLR9c40oiI8YGkg9N5Pz4xJia2vribTKfkA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-29T16:29:24Z"
    mac: ENC[AES256_GCM,data:tk5wyTCPxxzV6MSurESMM9L1CfY89HAH3viC3HCmb3ELqxVbEFAbwAxGnVZPBJsSRgDfwxNH/VUt9mCZuIkxle/m9kf6SZPB2Jc+GRfbtSFFMcU5vKTmbiLFtG4Kwkt2LpHACiaZQren3UGzUXrCP8ao/dtbBRKXDlLWKnznqDg=,iv:pHKu4tLAs/YhgN0hlEEJbdQCZdM69xGa/KHf4ZIDMEg=,tag:jrTbL04k0a2EEDkT8qEoAg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
