# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: github-token
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Ktm8HIjk4OxH+GiuDwYzMcdXIYsBSEQ9ZkW5tqrVgq3UkGAfup4QOQ==,iv:RIYHCTgDnuo7x80dhlglbcQQx5inXUziw8hmGM0bWL0=,tag:W5WH3BpECGLt7fO/RBrwmg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnOTdKTWJuQTZUYUd6bEo4
            N2ZHL1BjamhzMlBjRDZqblhVL050NFh6eVVFCnIxQTU4T2k4Ry9HWjAweWFTcnl5
            OHlwTE1vKzNEQW11eGRXZXpuSy8wMGcKLS0tIGpaeGFvZ3VsQUtFNlJFRW5TenRR
            bGJnL0RoU3R5bXJXNWVOWk9yeDI2ajgK7PlWFdgIAR6t/R168x5AaZJ6RgDR2bFl
            /Se7xAYViPz9WJQuZIl9ICBYe6YRkilt3OpTZajJVcH/rqbropmgZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-10T21:46:53Z"
    mac: ENC[AES256_GCM,data:E3MiqO4M0JbpYxlck2SEm5rr+lqXaLl7mCJp3lHqoXJdmVRBkm6krB4SJ8bi3uWGLjzldFQUs/a5GcQqdyqIO9fuYF32/IDXa6ZTkp3gVeNv0khmOs0nzCJsemly1W6qnzxI9ARf2XQHwVy5678523j/nYV2eCtwjM0N7570qMQ=,iv:bt9alb+pntMas4vmES1POUCe8UK5LKvqkxSu7Z8sSX8=,tag:7VLxISvm2DfkXHOeanMDpA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
