---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: networking
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      version: 0.12.1
      sourceRef:
        kind: HelmRepository
        name: metallb-charts
        namespace: flux-system
      interval: 5m
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    configInline:
      address-pools:
        - name: default
          protocol: layer2
          addresses:
            - "${METALLB_LB_RANGE}"
    # prometheusRule:
    #   enabled: true
    # prometheus:
    #   enabled: true
    #   serviceMonitor:
    #     enabled: true
    #   prometheusRule:
    #     enabled: true
    # controller:
    #   tolerations:
    #     - key: "arm"
    #       operator: "Exists"
    # speaker:
    #   tolerations:
    #     - key: "arm"
    #       operator: "Exists"
    #   nodeSelector:
    #     node_locality: internal
