---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - metallb-system
  - external-dns
  - k8s-gateway
  - error-pages
  - cloudflare-ddns
  - traefik
  # - traefik-forward-auth