---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: ${SETTING_CERT_MANAGER_CLUSTER_ISSUER_TEST}
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: "${SECRET_CLOUDFLARE_EMAIL}"
    privateKeySecretRef:
      name: ${SETTING_CERT_MANAGER_CLUSTER_ISSUER_TEST}
    solvers:
      - dns01:
          cloudflare:
            email: "${SECRET_CLOUDFLARE_EMAIL}"
            apiKeySecretRef:
              name: cloudflare-api-key
              key: api-key
        selector:
          dnsZones:
            - ${SECRET_DOMAIN}
