# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-token-secret
    namespace: cert-manager
stringData:
    cloudflare-token: ENC[AES256_GCM,data:LH6Gl+bvl559C4bJGt99zkBmB0tUkkHRUxLDMprCe+viKmti+w==,iv:ZdAU3Z3emuCf8BFpQXeNRr1Np52CXXLCvHHoSSQO6aQ=,tag:BYlJ8T5FmlFPagEYNbnmFg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5V0tWL2N5QzBsdndlR0R1
            c05VV1h2TzlpS0dQd2lQNDNhMThuSmNDRkZzCmRMOXFxY0NOazlTMlQvK2FrTGU3
            NlI0b0M2aXZCSlVOM1FNUE5zSUcySHMKLS0tIHBTeGxmYkFaUDhlaEFGRkNkZlRO
            WGVSZFNNSUF3cHRTWXZUTFlkbi9aVEkKdNYRU7kl7idS4a2MfHeDGTZ2mjnIhqhr
            kLpL8pJq3iTddhhvDOAg0XzZRfAarHVD8UgaT+zZiaKH6tRgzdJTTg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-08T16:11:19Z"
    mac: ENC[AES256_GCM,data:hsCa3TSWZaTV9tKCaA+/jsxiud3Z8SaU8xEeRwdoDI9djCWgcQeiySqOjZBt/NH8kIotOrqz9sUGmQAYwX5/PtSMM8VGOk3InWIDO46kqYdkoeI8C2ilzaA/52YuZ8DTg3iO8utC4QBdS+ekdrnMIFObab3SEXmgHALcLvzFjsM=,iv:+v9mn1CqC6MttQpZ4WhlIXiAeD5u7lUPQl/mV/Ui384=,tag:8dhO4Wz6Ff2ll//38z91bw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
