# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:Ho3/+wBs0x4qWHzrNjB7V/ucznAghOYzgENyNC2mPs4k5beT1g==,iv:HPNI5e6ei1D5lvFU0HA0PVgYbzoIm+4nc70vxPj0goE=,tag:jLTwYqy2cNjRyn2NrD7uKA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYU0VXdG5IRm1YWXVzQ0pk
            UFQwbW1yQXNkQi9QcXQ2dklJMWhVT2FWRDBvCkR1b3NCaGdtSUdETTI0dFBaWVNs
            MUpNNUZhaWxKL2Fiei93cjlLMnZUQ00KLS0tIFllOHNuSzIrUmJmV1Qwa1lPK0VY
            YWlHcVdJaDF5TnErQzk2NTdxYyt4MDQKhOg2acxdr9h1gY+KoWEabvQ/AQAw2ZLe
            7ywL+a+fQtT040xDPft3K9C77LpnBzTZKXnUd7MEAMLuVsnIqySoDw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-12T15:55:40Z"
    mac: ENC[AES256_GCM,data:JCm1ZQ78OD60xcAO5VSygPGk1/1fua+tBmf0TXEyAs027QFdbcBtnXTh64ntwYXLavbHD0HTRzEtsWtITzYssUtTDAs3fnRRSVm9E5VgaAFhPPU2cAmDmCVWbz+Y6XGVGcHVPqTwZxv7ANS66uQKAxgVq4ssYOM2JwNzMrBEiYo=,iv:A+wlNldnFTpCwbfH1FHysSIud5Ze8oyA1HMuzxAWcP8=,tag:2h/b5Q5rBDUmx91+2oRrtA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
