# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:g/81n0hAT9D/XtK3HcIjw7VGxasrMZFThxAk3en/jvytOGvPmQ==,iv:sK5jtzppKtBGRo0UulMZyq9QZegs4szokJ2xXAXnCUA=,tag:ejzizg3FV04dNzAVzb6qwg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoN2prdE83MW1QTlBVcW9P
            KzZPUVlqSkxYM3Q4Y1JDaXFKTmowV2M1WkVvCmJ0ZXFHd3NmZFROOE9OZWlGNW5E
            Q09icEZWWU1ENzlVazJaeEF6RDVLL00KLS0tIHlENVlBNGlBT284cUtBTDFIUnB1
            L1c4SXN3dldjN3E4MUdFQ1drYVZCSWsKGxnn5OtFbWRPAKCnMecRvxwz/X1w+YTz
            pljWLVn1jyTeNh7W2hgQ1xZo/F+k8WcmN351B6oFXnRI3T/a4K0XVw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-29T16:29:24Z"
    mac: ENC[AES256_GCM,data:Iu8ooLQMEjAzCCGXefojjZ3F1I5DyDdl9rUNFCSL+c4EjQAVavc1WouQRSYw+VJYlI4NoELqoevLrK6kG9D/56kBM+cQWGW7NfjVyMDHs0a+Xj/nDqeXFXqzGCdoc43wVZcmltVx2JfDiWhmIt/KAft7nWiD0JBGcosZM7v6QCw=,iv:1yS0NCG8+RFMK0Saeckvn4BehjitYw5T2Y/5RHsuLZc=,tag:NngvfP72WrefjqbPhOx8Kw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
