# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:rMoUGm2rFnKITPGvdRbLku3j9qEaKQ==,iv:V5JrdIM7jWAESi9lc1BethpzfOWWCb8i0Jk2xND5FDY=,tag:siFHm53Rd0T8S1ywMNwyCQ==,type:str]
    api-key: ENC[AES256_GCM,data:5F/ecn1esErI2UMRYkmhpyzf3ecZEAxMgqr1h9k0Ds9SC6oZSA==,iv:OXC+zwKgYfj362pWcjlAjIYTvrDzH5vcGszhbmLkZ6o=,tag:lmHAkXL+IZEswtgORL4rJw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1npf9h66hz7x4rzkghs6gpu52nhe9spxd2cxd6km6v97n0vlvcvasge4whr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoMUkzQmp0M2E1ZUJYRFdz
            OS8rVlkvdlE4dDR0NzM4QUFYcjNVRFNnZzNNCm5JU3pMR0w5ZnFpNERuLzQ2NkVL
            bzNzY3VhUjRXSGpEckN1VUwvUVlSRzgKLS0tIFRQVTJGZmVxSmhpUFVFSEVXL2dO
            SVU2a2FLYUp3bnJIR2d4RjVLUFZpVTgKBMyh8r3IBPB/mJqZeIi+CV8L9cdin2yF
            8g0yCZso/ne4NJHvj6TApu6aSwvnV916N6Qg8YrDclY8U2HF24a/0w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-06-15T06:59:49Z"
    mac: ENC[AES256_GCM,data:CkGPy61i0ehrDxrFLqsGqpl+Rpf7WtC7WX2O3AhEoeey3JRqLPJgrtxiCcNZB/QypQaZIPKfxYqLDZWImWd44b/bxft1Zpg4YFMYtj5e2fFm9kvaHUFDqHQq+k5l9Swe7QVXXPguN6q4mhhXK54wknnoXVg3vEo0oGilw1BL4co=,iv:hbqqX+s+NThv284cM089BZXvRxCoXNov0zq9FPXxom8=,tag:c2QcHfhqfDrEeKZ7zPkEdA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
